### ISSUE TITLE
Consistent Variable naming

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/DIDComm-js#18]
Right now in some cases variables use camel case and some use snake case. This library should support a consistent pattern and stick to it.

**Comment by flagoon** [comment]
I would like to tackle this. Can I take it?

**Comment by flagoon** [comment]
https://github.com/decentralized-identity/DIDComm-js/pull/19 
Thank you.

**Comment by kdenhartog** [comment]
Thanks!
