### ISSUE TITLE
Separate pack_auth_msg?

### ISSUE THREAD

**Issue by dbluhm** [decentralized-identity/DIDComm-js#7]
I'm confused by the separate pack_auth_msg method included in the library. What is the purpose of having it separated from packMessage? It would be good to have clearer documentation on the reasoning.

**Comment by kdenhartog** [comment]
I can add additional documentation. For the sake of getting an answer though, the purpose is to create a distinction between a message using Authcrypt and one using Anoncrypt which guarantee different properties. The original packMessage conflated the two ideas and this separation of concern feels like a better approach for distinguishing between the two ideas.

However, the unpackMessage functionality won't change making for easy processing on the receiver side.
